# Generated by Django 4.2.14 on 2025-01-06 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('voucher_type', models.CharField(choices=[('Payment', 'Payment'), ('Receipt', 'Receipt'), ('Journal', 'Journal')], max_length=10)),
                ('category', models.CharField(choices=[('Cash Sheet', 'Cash Sheet'), ('Payment Sheet', 'Payment Sheet'), ('Collection Sheet', 'Collection Sheet'), ('Loan', 'Loan'), ('Cash and Bank', 'Cash and Bank'), ('Manual', 'Manual')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_vouchers', to='dashboard.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_collection', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('special_record', models.CharField(blank=True, choices=[('A', 'A'), ('P', 'P'), ('L', 'L'), ('S', 'S'), ('D', 'D'), ('B', 'B'), ('M', 'M'), ('E', 'E')], default='P', max_length=100, null=True)),
                ('meeting_no', models.IntegerField(default=1)),
                ('meeting_date', models.DateField()),
                ('evaluation_no', models.IntegerField()),
                ('next_meeting_date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('Saved', 'Saved'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled')], default='Saved', max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_sheets', to='dashboard.branch')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_sheets', to='dashboard.center')),
                ('meeting_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_sheets', to='dashboard.member')),
                ('supervision_by_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_sheet_supervisor_1', to=settings.AUTH_USER_MODEL)),
                ('supervision_by_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_sheet_supervisor_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.branch')),
            ],
        ),
    ]
