# Generated by Django 4.2.14 on 2024-11-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='category',
            field=models.CharField(choices=[('Cash Sheet', 'Cash Sheet'), ('Payment Sheet', 'Payment Sheet'), ('Loan', 'Loan'), ('Cash and Bank', 'Cash and Bank'), ('Manual', 'Manual')], max_length=30),
        ),
    ]
