# Generated by Django 4.2.14 on 2024-12-04 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_center_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_voucher_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_collection', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('special_record', models.CharField(blank=True, choices=[('A', 'A'), ('P', 'P'), ('L', 'L'), ('S', 'S'), ('D', 'D'), ('B', 'B'), ('M', 'M'), ('E', 'E')], default='P', max_length=100, null=True)),
                ('meeting_no', models.IntegerField(default=1)),
                ('meeting_date', models.DateField()),
                ('evaluation_no', models.IntegerField()),
                ('next_meeting_date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled')], default='saved', max_length=100)),
                ('Center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_sheets', to='dashboard.center')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_sheets', to='dashboard.branch')),
                ('meeting_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_sheets', to='dashboard.member')),
                ('supervision_by_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_sheet_supervisor_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
