# Generated by Django 4.2.14 on 2025-01-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cashvault_dailycashsummary_teller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsheet',
            name='meeting_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='category',
            field=models.CharField(choices=[('Cash Sheet', 'Cash Sheet'), ('Payment Sheet', 'Payment Sheet'), ('Collection Sheet', 'Collection Sheet'), ('Loan', 'Loan'), ('Cash and Bank', 'Cash and Bank'), ('Service Fee', 'Service Fee'), ('Manual', 'Manual')], max_length=30),
        ),
    ]
