# Generated by Django 4.2.14 on 2025-02-21 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_collectionsheet_meeting_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='description',
            new_name='narration',
        ),
        migrations.AddField(
            model_name='voucher',
            name='cheque_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='encloser',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='in_word',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='VoucherEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6)),
                ('memo', models.TextField(blank=True, null=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.voucher')),
            ],
        ),
    ]
