# Generated by Django 4.2.14 on 2024-12-07 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_collectionsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionsheet',
            name='supervision_by_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_sheet_supervisor_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collectionsheet',
            name='supervision_by_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='collection_sheet_supervisor_1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
