# Generated by Django 4.2.14 on 2025-02-23 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_rename_description_voucher_narration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherentry',
            name='account',
        ),
        migrations.AddField(
            model_name='voucherentry',
            name='content_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucherentry',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
