# Generated by Django 4.2.14 on 2025-02-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_voucherentry_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashvault',
            old_name='current_balance',
            new_name='balance',
        ),
    ]
