# Generated by Django 4.2.14 on 2024-12-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_collectionsheet_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionsheet',
            old_name='Center',
            new_name='center',
        ),
    ]
