# Generated by Django 4.2.14 on 2025-03-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_current_balance_cashvault_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='category',
            field=models.CharField(choices=[('Cash Sheet', 'Cash Sheet'), ('Payment Sheet', 'Payment Sheet'), ('Collection Sheet', 'Collection Sheet'), ('Loan', 'Loan'), ('Cash and Bank', 'Cash and Bank'), ('Service Fee', 'Service Fee'), ('Saving Interest', 'Saving Interest'), ('Tax Charges', 'Tax Charges'), ('Manual', 'Manual')], max_length=30),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Receipt', 'Receipt'), ('Journal', 'Journal'), ('Other', 'Other')], max_length=10),
        ),
    ]
