# Generated by Django 4.2.14 on 2025-03-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_voucher_category_alter_voucher_voucher_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashvault',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
