# Generated by Django 4.2.14 on 2025-01-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cashvault_teller_alter_voucher_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teller',
            name='pending_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
