# Generated by Django 4.2.14 on 2025-01-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_teller_pending_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashvault',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='vaulttransaction',
            name='created_by',
        ),
        migrations.AddField(
            model_name='cashvault',
            name='pending_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tellertotellertransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='vaulttransaction',
            name='deposited_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vaulttransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='cashvault',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
