# Generated by Django 4.2.14 on 2024-10-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('CS', 'Complusory Saving'), ('CF', 'Center Fund'), ('RTR', 'Optional Saving'), ('SBK', 'Samayojan Bachhat Khata')], default='CS', max_length=50)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.member')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField(help_text='Duration in months')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_deposits', to='dashboard.member')),
            ],
        ),
        migrations.CreateModel(
            name='FixedDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maturity_date', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_deposits', to='dashboard.member')),
            ],
        ),
    ]
