# Generated by Django 5.1 on 2024-11-17 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsaccount',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SavingsAccount', to='dashboard.member'),
        ),
    ]
