# Generated by Django 5.1 on 2024-10-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccount',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('IA', 'In-Active')], default='A', max_length=25),
        ),
    ]
