# Generated by Django 4.2.14 on 2025-02-28 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashsheet',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashsheets', to='savings.savingsaccount'),
        ),
        migrations.AlterField(
            model_name='paymentsheet',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentsheets', to='savings.savingsaccount'),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'In-Active'), ('closed', 'Closed')], default='active', max_length=25),
        ),
    ]
