# Generated by Django 4.2.14 on 2024-12-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_alter_savingsaccount_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='category',
            field=models.CharField(choices=[('Cash Sheet', 'Cash Sheet'), ('Payment Sheet', 'Payment Sheet'), ('Loan', 'Loan'), ('Charge', 'Charge'), ('Collection', 'Collection')], default='test', max_length=50),
            preserve_default=False,
        ),
    ]
