# Generated by Django 5.1 on 2024-10-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_savingsaccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=4),
        ),
    ]
