# Generated by Django 4.2.14 on 2025-03-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_alter_cashsheet_account_alter_paymentsheet_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='category',
            field=models.CharField(choices=[('Cash Sheet', 'Cash Sheet'), ('Payment Sheet', 'Payment Sheet'), ('Loan', 'Loan'), ('Charge', 'Charge'), ('Tax Charges', 'Tax Charges'), ('Collection', 'Collection'), ('Interest', 'Interest')], max_length=50),
        ),
    ]
