# Generated by Django 5.1 on 2024-10-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_savingsaccount_amount_savingsaccount_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
