# Generated by Django 5.1 on 2024-10-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_alter_savingsaccount_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsaccount',
            name='account_type',
            field=models.CharField(choices=[('CS', 'Compulsory Saving'), ('CF', 'Center Fund'), ('OS', 'Optional Saving'), ('SBK', 'Samayojan Bachhat Khata'), ('CHS', 'Child Saving'), ('IS', 'Insurance Saving'), ('FS', 'Fixed Saving')], default='CS', max_length=50),
        ),
    ]
