# Generated by Django 5.1 on 2024-11-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0010_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='transaction_date',
            field=models.DateTimeField(),
        ),
    ]
