# Generated by Django 5.1 on 2024-11-13 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_voucher_category'),
        ('savings', '0012_statement_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_stat', to='savings.savingsaccount'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_statement', to='core.voucher'),
        ),
    ]
