# Generated by Django 4.2.14 on 2025-01-19 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='dashboard.branch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_detail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='relationship',
            field=models.CharField(choices=[('Father', 'Father'), ('Husband', 'Husband'), ('Father-In-Law', 'Father-In-Law'), ('Wife', 'Wife'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Mother', 'Mother'), ('Mother-In-Law', 'Mother-In-Law'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Grandfather', 'Grandfather'), ('Grandmother', 'Grandmother'), ('Uncle', 'Uncle'), ('Aunt', 'Aunt'), ('Grandson', 'Grandson'), ('Granddaughter', 'Granddaughter'), ('Nephew', 'Nephew'), ('Niece', 'Niece'), ('Cousin', 'Cousin'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='middle_name',
            field=models.CharField(blank=True, default='kumar', max_length=50),
            preserve_default=False,
        ),
    ]
