# Generated by Django 4.2.14 on 2024-12-04 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'ordering': ['formed_date']},
        ),
        migrations.AddField(
            model_name='expensesinformation',
            name='clothes_expenses',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='expensesinformation',
            name='communication_expenses',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='expensesinformation',
            name='education_expenses',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='expensesinformation',
            name='entertaiment_expenses',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='expensesinformation',
            name='festival_expenses',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='expensesinformation',
            name='fuel_expenses',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='incomeinformation',
            name='business_income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='incomeinformation',
            name='government_post',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='incomeinformation',
            name='other',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='incomeinformation',
            name='pension',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='incomeinformation',
            name='personal_job_income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='incomeinformation',
            name='wages_income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='group',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='dashboard.center'),
        ),
    ]
