# Generated by Django 5.1 on 2024-11-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensesinformation',
            old_name='food_expense',
            new_name='clothes_expenses',
        ),
        migrations.RenameField(
            model_name='expensesinformation',
            old_name='health_expense',
            new_name='communication_expenses',
        ),
        migrations.RenameField(
            model_name='expensesinformation',
            old_name='house_rent',
            new_name='education_expenses',
        ),
        migrations.RenameField(
            model_name='incomeinformation',
            old_name='cattle_income',
            new_name='abroad_employment_income',
        ),
        migrations.RenameField(
            model_name='incomeinformation',
            old_name='earning',
            new_name='agriculture_income',
        ),
        migrations.RenameField(
            model_name='incomeinformation',
            old_name='farming_income',
            new_name='animal_farming_income',
        ),
        migrations.AddField(
            model_name='expensesinformation',
            name='entertaiment_expenses',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='expensesinformation',
            name='festival_expenses',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='expensesinformation',
            name='fuel_expenses',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='expensesinformation',
            name='health_expenses',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='expensesinformation',
            name='house_expenses',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='incomeinformation',
            name='business_income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='incomeinformation',
            name='government_post',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='incomeinformation',
            name='other',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='incomeinformation',
            name='pension',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='incomeinformation',
            name='personal_job_income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='incomeinformation',
            name='wages_income',
            field=models.FloatField(default=0.0),
        ),
    ]
