# Generated by Django 5.1 on 2024-08-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_center_no_of_group_center_no_of_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
