# Generated by Django 4.2.14 on 2024-12-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_food_expense_expensesinformation_clothes_expenses_and_more'),
        ('dashboard', '0003_alter_center_formed_date_alter_center_from_date_and_more'),
    ]

    operations = [
    ]
