# Generated by Django 5.1 on 2024-10-31 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_addressinformation_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressinformation',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addressInfo', to='dashboard.member'),
        ),
    ]
