# Generated by Django 4.2.14 on 2024-12-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_food_expense_expensesinformation_health_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesinformation',
            name='clothes_expenses',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='expensesinformation',
            name='communication_expenses',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='expensesinformation',
            name='education_expenses',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='expensesinformation',
            name='entertaiment_expenses',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='expensesinformation',
            name='festival_expenses',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='expensesinformation',
            name='fuel_expenses',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='expensesinformation',
            name='health_expenses',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='expensesinformation',
            name='house_expenses',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='expensesinformation',
            name='other_expenses',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='incomeinformation',
            name='abroad_employment_income',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='incomeinformation',
            name='agriculture_income',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='incomeinformation',
            name='animal_farming_income',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='incomeinformation',
            name='business_income',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='incomeinformation',
            name='government_post',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='incomeinformation',
            name='other',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='incomeinformation',
            name='pension',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='incomeinformation',
            name='personal_job_income',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='incomeinformation',
            name='wages_income',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
