# Generated by Django 4.2.14 on 2025-02-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_addressinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dropout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='registered_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
