# Generated by Django 4.2.14 on 2025-02-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_member_dropout_date_member_registered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='registered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
