# Generated by Django 5.1 on 2024-08-26 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_group_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.center'),
        ),
        migrations.AddField(
            model_name='member',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='expensesinformation',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expensesInfo', to='dashboard.member'),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='familyInfo', to='dashboard.member'),
        ),
        migrations.AlterField(
            model_name='houseinformation',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='houseInfo', to='dashboard.member'),
        ),
        migrations.AlterField(
            model_name='incomeinformation',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incomeInfo', to='dashboard.member'),
        ),
        migrations.AlterField(
            model_name='landinformation',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landInfo', to='dashboard.member'),
        ),
        migrations.AlterField(
            model_name='livestockinformation',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livestockInfo', to='dashboard.member'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personalInfo', to='dashboard.member'),
        ),
    ]
