# Generated by Django 4.2.14 on 2025-02-12 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0005_alter_member_registered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='member/personal/'),
        ),
        migrations.CreateModel(
            name='PersonalMemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Citizenship', 'Citizenship'), ('Passport', 'Passport'), ('Voter ID', 'Voter ID'), ('Driver License', 'Driver License')], max_length=50)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='member/personal/')),
                ('uploaded_date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_documents', to='dashboard.member')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_member_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to='member/family/')),
                ('uploaded_date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_documents', to='dashboard.member')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_family_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
