# Generated by Django 5.1 on 2024-10-02 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_member_center_member_code_member_member_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='center',
            name='created_on',
        ),
        migrations.AddField(
            model_name='center',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='center',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('public', 'Public'), ('business', 'Business'), ('others', 'Others')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centerdistrict', to='dashboard.district'),
        ),
        migrations.AddField(
            model_name='center',
            name='every',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='formed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='center',
            name='formed_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='from_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='grt_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grt_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='center',
            name='meeting_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='center',
            name='meeting_date',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='meeting_distance',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='meeting_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='meeting_interval',
            field=models.IntegerField(choices=[(14, '14 days'), (28, '28 days')], default=14, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='meeting_place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='meeting_repeat_type',
            field=models.CharField(choices=[('fixed interval', 'Fixed Interval'), ('fixed date', 'Fixed Date')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='meeting_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='meeting_start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centermunicipality', to='dashboard.municipality'),
        ),
        migrations.AddField(
            model_name='center',
            name='pgt_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pgt_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='center',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centerprovince', to='dashboard.province'),
        ),
        migrations.AddField(
            model_name='center',
            name='to_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='walking_time',
            field=models.TimeField(null=True),
        ),
    ]
