# Generated by Django 4.2.14 on 2024-09-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_member_center_member_code_member_member_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='tole',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='wardNo',
        ),
        migrations.AddField(
            model_name='branch',
            name='tole',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='wardNo',
            field=models.IntegerField(default=1),
        ),
    ]
