# Generated by Django 4.2.14 on 2025-02-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_personalinformation_photo_personalmemberdocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='member/personal/'),
        ),
    ]
