# Generated by Django 4.2.14 on 2025-02-12 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_personalinformation_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalmemberdocument',
            name='uploaded_date',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
