# Generated by Django 5.1 on 2024-10-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_municipality_tole_remove_municipality_wardno_and_more'),
        ('dashboard', '0008_center_input_code_alter_center_code'),
    ]

    operations = [
    ]
