# Generated by Django 5.1 on 2024-10-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_merge_20241004_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('public', 'Public'), ('business', 'Business'), ('others', 'Others')], default='general', max_length=15),
        ),
    ]
