# Generated by Django 4.2.14 on 2025-03-20 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymemberdocument',
            name='uploaded_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 3, 20, 7, 39, 50, 730300, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
