# Generated by Django 5.1 on 2024-10-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_center_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
