# Generated by Django 5.1 on 2024-10-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_group_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('PUBLIC', 'Public'), ('BUSINESS', 'Business'), ('OTHERS', 'Others')], default='general', max_length=15),
        ),
    ]
