# Generated by Django 4.2.14 on 2025-03-20 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0011_alter_familymemberdocument_uploaded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymemberdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_family_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalmemberdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_member_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
