# Generated by Django 5.1 on 2024-10-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_center_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_category',
            field=models.CharField(default='General Member', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
