# Generated by Django 5.1 on 2024-10-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_member_member_category_member_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('IA', 'In-Active'), ('RTR', 'Ready To Register'), ('D', 'Dropout'), ('p', 'Public'), ('D', 'Death')], default='RTR', max_length=25),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_category',
            field=models.CharField(choices=[('General Member', 'General Member'), ('Public Member', 'Public Member')], default='General Member', max_length=20),
        ),
    ]
