# Generated by Django 5.1 on 2024-10-07 12:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_member_member_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyinformation',
            name='daughters',
        ),
        migrations.RemoveField(
            model_name='familyinformation',
            name='father',
        ),
        migrations.RemoveField(
            model_name='familyinformation',
            name='husband',
        ),
        migrations.RemoveField(
            model_name='familyinformation',
            name='sons',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='permanent_address',
        ),
        migrations.AddField(
            model_name='familyinformation',
            name='citizenship_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='familyinformation',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familyinformation',
            name='education',
            field=models.CharField(choices=[('Illiterate', 'Illiterate'), ('Literate', 'Literate'), ('Under SLC', 'High'), ('SLC', 'SLC'), ('Intermediate', 'Intermediate'), ('Bachelor', 'Bachelor'), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='familyinformation',
            name='family_member_name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familyinformation',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familyinformation',
            name='issued_from',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='familyinformation',
            name='monthly_income',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='familyinformation',
            name='occupation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='familyinformation',
            name='phone_number',
            field=models.IntegerField(default=1234567890, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familyinformation',
            name='relationship',
            field=models.CharField(choices=[('Father', 'Father'), ('Husband', 'Husband'), ('Father-In-Law', 'Father-In-Law'), ('Son', 'Son'), ('Daughter', 'Daughter')], default='Father', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='citizenship_no',
            field=models.CharField(default=-1018, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='education',
            field=models.CharField(choices=[('Illiterate', 'Illiterate'), ('Literate', 'Literate'), ('Under SLC', 'High'), ('SLC', 'SLC'), ('Intermediate', 'Intermediate'), ('Bachelor', 'Bachelor'), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.')], default='Literate', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='family_member_no',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='family_status',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Medium', 'Medium'), ('High', 'High'), ('Rich', 'Rich')], default='Medium', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='file_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='first_name',
            field=models.CharField(default='New', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Female', max_length=15),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='issued_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='issued_from',
            field=models.CharField(default='Nepal', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='last_name',
            field=models.CharField(default='User', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widow', 'Widow')], default='Single', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='marriage_reg_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='marriage_regd_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='middle_name',
            field=models.CharField(default='middle', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='occupation',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Business', 'Buddhism'), ('Housewife', 'Housewife'), ('Foreign Employment', 'Foreign Employment')], default='Housewife', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='registered_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='registered_vdc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='religion',
            field=models.CharField(choices=[('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Kirat', 'Kirat'), ('Christainity', 'Christainity'), ('Islam', 'Islam'), ('Jainism', 'Jainism'), ('Bon', 'Bon')], default='Hinduism', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='voter_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='voter_id_issued_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='phone_number',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='AddressInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent_ward_no', models.IntegerField(default=1)),
                ('permanent_tole', models.CharField(max_length=50)),
                ('permanent_house_no', models.CharField(blank=True, max_length=50, null=True)),
                ('current_ward_no', models.IntegerField(default=1)),
                ('current_tole', models.CharField(max_length=50)),
                ('current_house_no', models.CharField(blank=True, max_length=50, null=True)),
                ('old_ward_no', models.IntegerField(default=1)),
                ('old_tole', models.CharField(max_length=50)),
                ('old_house_no', models.CharField(blank=True, max_length=50, null=True)),
                ('current_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_current_district', to='dashboard.district')),
                ('current_municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_current_municipality', to='dashboard.municipality')),
                ('current_province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_current_province', to='dashboard.province')),
                ('old_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_old_district', to='dashboard.district')),
                ('old_municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_old_municipality', to='dashboard.municipality')),
                ('old_province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_old_province', to='dashboard.province')),
                ('permanent_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_permanent_district', to='dashboard.district')),
                ('permanent_municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_permanent_municipality', to='dashboard.municipality')),
                ('permanent_province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_permanent_province', to='dashboard.province')),
            ],
        ),
    ]
