# Generated by Django 5.1 on 2024-10-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_familyinformation_daughters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
