# Generated by Django 5.1 on 2024-10-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_personalinformation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinformation',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
