# Generated by Django 5.1 on 2024-10-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    # dependencies = [
    #     ('dashboard', '0019_alter_familyinformation_phone_number'),
    # ]

    operations = [
        migrations.AlterField(
            model_name='familyinformation',
            name='education',
            field=models.CharField(blank=True, choices=[('Illiterate', 'Illiterate'), ('Literate', 'Literate'), ('Under SLC', 'High'), ('SLC', 'SLC'), ('Intermediate', 'Intermediate'), ('Bachelor', 'Bachelor'), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='monthly_income',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='occupation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
