# Generated by Django 5.1 on 2024-10-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_familyinformation_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinformation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familyInfo', to='dashboard.member'),
        ),
    ]
