# Generated by Django 5.1 on 2024-11-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
