# Generated by Django 4.2.14 on 2024-10-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emipayment',
            name='interest_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='emipayment',
            name='principal_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
