# Generated by Django 4.2.14 on 2025-01-22 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cashvault_dailycashsummary_teller_and_more'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emipayment',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emi_payments', to='core.voucher'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('flat', 'Flat Interest'), ('declining', 'Declining Balance'), ('interest_only', 'Interest Only')], max_length=20),
        ),
    ]
