# Generated by Django 4.2.14 on 2025-02-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_emipayment_voucher_alter_loan_loan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('Flat', 'Flat Interest'), ('Declining', 'Declining Balance'), ('Interest_Only', 'Interest Only')], max_length=20),
        ),
    ]
