# Generated by Django 4.2.14 on 2024-11-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_emipayment_interest_paid_emipayment_principal_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
