# Generated by Django 4.2.14 on 2024-11-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='start_date',
            new_name='loan_demand_date',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='end_date',
            new_name='loan_disburse_date',
        ),
        migrations.AddField(
            model_name='loan',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_analysis_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_analysis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_purpose',
            field=models.CharField(choices=[('Crop and Crop Services', 'Crop and Crop Services'), ('Wholesale and Retail Business', 'Wholesale and Retail Business'), ('Hotel and Restaurants', 'Hotel and Restaurants'), ('Fruits and Flowers', 'Fruits and Flowers'), ('Animal Husbandary', 'Animal Husbandary'), ('Poultry', 'Poultry'), ('Other Agricultural and Agro Services', 'Other Agricultural and Agro Services'), ('Other Services', 'Other Services')], default='Crop and Crop Services', max_length=50),
            preserve_default=False,
        ),
    ]
