# Generated by Django 4.2.14 on 2025-03-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanprocessing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanprocessing',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('analysis', 'Analysis'), ('disburse', 'Disburse'), ('approved', 'Approved'), ('active', 'Active'), ('processed', 'Processed')], default='applied', max_length=100),
        ),
    ]
