# Generated by Django 4.2.14 on 2024-11-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_rename_start_date_loan_loan_demand_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('analysis', 'Analysis'), ('disburse', 'Disburse'), ('active', 'Active'), ('closed', 'Closed')], default='applied', max_length=100),
        ),
    ]
