# Generated by Django 4.2.14 on 2024-11-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_loan_interest_rate_alter_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='duration_months',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
