# Generated by Django 4.2.14 on 2024-11-28 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_alter_loan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMIPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('principal_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_payments', to='loans.loan')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='payments',
            field=models.ManyToManyField(blank=True, related_name='loans', to='loans.emipayment'),
        ),
    ]
