# Generated by Django 4.2.14 on 2024-11-30 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0008_emipayment_loan_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
