# Generated by Django 4.2.14 on 2024-12-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_loan_created_by_loan_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='installement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
