# Generated by Django 4.2.14 on 2024-12-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_loan_installement_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='installement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
