# Generated by Django 4.2.14 on 2025-01-19 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_cashvault_last_updated_by_and_more'),
        ('loans', '0011_alter_loan_installement_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='emipayment',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.voucher'),
        ),
    ]
